FROM ubuntu 

RUN apt-get update && apt-get install -y nodejs && apt-get install -y dnsutils && apt-get install -y iputils-ping
WORKDIR /home/node

COPY . .

#RUN npm install

CMD ["nodejs", "index.js"]

